### ISSUE TITLE
started event listener completes before first tick event is thrown?

### ISSUE THREAD

**Issue by dkebler** [onury/tasktimer#1]
If I set a listener to the started event will it keep the first tick event from being emitted until the attached listener function resolves (mine is promise)?

If not then how can I do some initialization right before the timer actually starts emitting ticks,  I can see this being a bug if the that promise doesn't resolve before the first tick fires,  my interval is short 300ms.

**Comment by onury** [comment]
TaskTimer is time-based, by design. It will only fire (theoretically) on-time — on the given tick interval. It will not wait/schedule for the functions called within the task `callback`, to complete.

It seems what you need is an event-based runner. Next callback fires when the previous completes. Is this what you need?

If the problem is to first call an initial promise function and start TaskTimer when it resolves, then you can try this:
```js
var timer = new TaskTimer(300),
    task1 = yourTask;

promiseFn()
    .then(function (result) {
        timer.addTask(task1).start();
    });
```
Let me know if I got you right.

**Comment by dkebler** [comment]
Yes just need it to wait once before actually starting so that works.  Definitely need the timer not an event based runner.  

----
Yea your code actually starts the timer before even emitting "started"
```
    start() {
        this._stop();
        this._.startTime = Date.now();
        this._.stopTime = 0;
        this._.tickCount = 0;
        this._run();
        this._.state = TaskTimer.State.RUNNING;
        this.emit(TaskTimer.Event.STARTED);
        return this;
}
```
