### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by andreddosantos** [onury/tasktimer#10]
Hello guys,

I'm currently experiencing an error when i run the timer for 1 or 2 hours.

```
RangeError: Maximum call stack size exceeded
>     at t._run (/node_modules/tasktimer/lib/tasktimer.min.js:1:6100)
>     at i._tick (/node_modules/tasktimer/lib/tasktimer.min.js:1:11704)
>     at /node_modules/tasktimer/lib/tasktimer.min.js:1:12424
>     at Object.setImmediate (/node_modules/tasktimer/lib/tasktimer.min.js:1:1913)
>     at i._run (/node_modules/tasktimer/lib/tasktimer.min.js:1:12314)
>     at i._tick (/node_modules/tasktimer/lib/tasktimer.min.js:1:11878)
>     at /node_modules/tasktimer/lib/tasktimer.min.js:1:12424
>     at Object.setImmediate (/node_modules/tasktimer/lib/tasktimer.min.js:1:1913)
>     at i._run (/node_modules/tasktimer/lib/tasktimer.min.js:1:12314)
```

Do you have any ideia on this issue?

Regards 
André

**Comment by onury** [comment]
This library is being used in production and have been tested to run without any issues for months.

What's your configuration? Can you provide some code? How can we reproduce your issue?

**Comment by andreddosantos** [comment]
@onury I've made some refactoring in my code. In some quick tests i wasn't able to replicate anymore. Let me perform some heavier test and i'll let you know more about this issue if it still persists.

Regards
André

**Comment by onury** [comment]
Ok. re-open the issue if needed.

**Comment by bennidi** [comment]
I have the same issue in my code base. I run just one task every 5ms. This is what the code looks like:

```js
    let container = null // currently processed action
    this.scheduler = new TaskTimer(resolution)
    this.scheduler.on('tick', async () => {
      if (container) return
      if (this.queue.isEmpty()) return
      container = this.queue.dequeue()
      const action = container.action
      const context = ActionContext(ctrl, { log })
      const actions = findMatchingActions(action, this.descriptors) // match based on requested action
      try {
        // Sequential processing of action loop phases
        this.log.info(`Processing ${actions.length} time(s)`, action )
        await Promise.all(preparation(actions, action, context))
        await this.bus.command('brix/al/post-prepare').publish({ action, context })
        await Promise.all(processing(actions, action, context))
        await this.bus.command('brix/al/post-process').publish({ action, context })
        await Promise.all(cleanup(actions, action, context))
        await this.bus.command('brix/al/post-cleanup').publish({ action, context })
      } catch (error) {
        this.log.error(error)
        container.reject(error)
      } finally {
        container.resolve()
        container = null
      }
    })
    this.scheduler.start()

```

After the app stayed open in the browser for about 2 hours, the error is thrown and execution stops. Since I do not have any recursive code running or tasks that depend on other tasks or anything, I believe there must be something in the library that causes this behaviour. Any ideas?

I am using version 3.0.0

**Comment by onury** [comment]
First of all, you said running a task every 5 milliseconds. That's 200 calls per second, ~1.5 million calls in 2 hours; and you have lots of calls within the task. Are you sure about this? That would require a very powerful CPU and very fast network connection.

And secondly, did you make sure the max. call stack error is thrown due to TaskTimer? Where does the error stack point to? There are lots of sync and async calls within your handler.

Can you try the same exact example using `setTimeout` or `setInterval` (instead of TaskTimer) and see if it still throws the same error. I suspect it will.

**Comment by bennidi** [comment]
Yes, I think I can easily switch the code to use setInterval instead. Regarding your hypothesis: The handler will return immediately if the queue is empty. In my scenario, the queue is empty almost all the time, because only user interaction will dispatch actions through the queue. The above error occurs when I leave the app open without any interaction. So that makes 200 Noops per second. The async calls that you see are only run if an action is dispatched. The complexity of each async call is generally very low. They usually set only some properties but since some of them might do IO they are run with async/await.
Your statement about powerful CPU and very fast network connection, I don't understand at all. What network? Everything is running locally without IO. IMHO, 200 calls per second to small and JIT optimized code with most of the data in CPU cache is not a real load to any modern computer.

**Comment by onury** [comment]
@bennidi I don't have any knowledge about your code. Some of those calls (`processing()`, `command()`, `cleanup()`..) might have been requesting a query from an external database, executing shell commands, hard processing on the results, etc.. 

Anyway, pls first check the call stack and where it points to. Is it TaskTimer or is it another method..
And since you're getting this max. call stack error after a period, and not on the initial call(s); it means it's adding up to the stack. Is there a recursion somewhere? (you might want to check the methods you're calling inside the timer handler)..

Let me know if you get the same error with `setInterval()`..

**Comment by bennidi** [comment]
So, I switched to `setInterval` since I currently only have this one task and the error disappeared?!
