### ISSUE TITLE
preformance: use requestAnimationFrame instead of setTimeout in browser enviroment

### ISSUE THREAD

**Issue by Wavez** [onury/tasktimer#14]
Hey 😀 first I wish to show my appreciation for this awesome library!
In regard to performance,
I've looked at the source code,
it seems tasktimer is optimized for node.js but not for browser environments.
It's more efficient and easier on the event loop to queue by the requestAnimationFrame() browser API than setTimeout, setInterval.

Please let me know your thoughts

**Comment by onury** [comment]
Thanks.

I don't think `requestAnimationFrame()` is better for performance. It'd be better for performance "optimization" (in terms of debouncing an operation) if you're working with animations. 

Since it does not have a delay time argument, it can only be used for recovering CPU/clock drifts in the context of TaskTimer. (like `setImmediate()` in node). In browser, we fallback to `setTimeout(fn, 0)`.

`requestAnimationFrame()` mostly runs 60 times per second (or whatever display refresh rate), which gives it around a minimum of ~16.67 milliseconds clamp. So if used, that might produce even more clock drifts. It's said that `setTimeout(fn, 0)` has 4 milliseconds clamp even after multiple nested timers (which is faster).

**Comment by onury** [comment]
Another note...

Since `requestAnimationFrame()` is meant for rendering the page/UI; it is **paused** by most browser if window/tab is not focused. 

So not a good idea to use it with a "task" timer, even if it was a valid choice.

**Comment by Wavez** [comment]
Thanks for the quick reply!
Everything you have mentioned is true, clear and solid.
I guess I should better phrase my question and use case.
I really like the API of task timer, and I was thinking to use it as a master timeline for a CSS animation trigger.
I was thinking about adding a requestAnimationFrame flag to tasktimer.
Would be happy to hear your thoughts

**Comment by onury** [comment]
I think you can still use TaskTimer as is and use the callbacks to trigger animations/transitions by switching classes. Also take a look at animo.js maybe..

**Comment by Wavez** [comment]
Think I'll just fork and play, maybe I'll come out with something cool :)
